//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sObjectOverlay) DeepCopyInto(out *K8sObjectOverlay) {
	*out = *in
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]*K8sObjectOverlayPatch, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(K8sObjectOverlayPatch)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sObjectOverlay.
func (in *K8sObjectOverlay) DeepCopy() *K8sObjectOverlay {
	if in == nil {
		return nil
	}
	out := new(K8sObjectOverlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sObjectOverlayPatch) DeepCopyInto(out *K8sObjectOverlayPatch) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sObjectOverlayPatch.
func (in *K8sObjectOverlayPatch) DeepCopy() *K8sObjectOverlayPatch {
	if in == nil {
		return nil
	}
	out := new(K8sObjectOverlayPatch)
	in.DeepCopyInto(out)
	return out
}
